# Generated by Django 5.0.7 on 2024-08-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfoliocertificate_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='', max_length=140),
        ),
    ]
