# Generated by Django 5.0.7 on 2024-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
